version: '3'
services:
  mysql:
    image: mysql:5
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: travellux
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: root
  api:
    depends_on:
      - mysql
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 3000:3000
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: mysql_user
      DB_PASSWORD: mysql_password
      DB_NAME: travellux
      JWT_SECRET: luxtravelsecretKey
      MAIL_HOST: smtp.gmail.com
      MAIL_USER: travellux.donotreplay@gmail.com
      MAIL_PASSWORD: travelluxwebwork
      MAIL_FROM: travellux.donotreplay@gmail.com
  booking-service:
    depends_on:
      - mysql
    container_name: booking-service
    build:
      dockerfile: Dockerfile
      context: ./booking-service
    ports:
      - 3050:3050
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: mysql_user
      DB_PASSWORD: mysql_password
      DB_NAME: travellux
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 4000:80
    environment:
      BOOKING_HOST: localhost
      BOOKING_PORT: 3050
      BACKEND_HOST: localhost
      BACKEND_PORT: 3000
  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql
      environment:
        ADMINER_DEFAULT_SERVER: mysql