apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    editable: true

  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: "traceID"
          matcherRegex: "traceID=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: jaeger
    editable: true
